using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Cysharp.Runtime.Multicast.CodeGen;

internal static class ProxyEmitter
{
    public static string Emit(string namespaceName, string anchorName, IReadOnlyList<ReceiverDefinition> receivers)
    {
        var builder = new StringBuilder();
        builder.AppendLine("""
            // <auto-generated />
            #nullable enable
            """);
        if (!string.IsNullOrEmpty(namespaceName))
        {
            builder.AppendLine($"namespace {namespaceName};");
            builder.AppendLine();
        }

        var factoryName = $"__MulticasterProxyFactory_{Sanitize(anchorName)}";
        EmitFactory(builder, factoryName, receivers);
        EmitAnchor(builder, anchorName, factoryName);
        return builder.ToString();
    }

    private static void EmitInMemoryProxy(StringBuilder builder, ReceiverDefinition receiver)
    {
        builder.AppendLine($$"""
                internal sealed class {{receiver.ProxyName}}InMemoryProxy<TKey> : global::Cysharp.Runtime.Multicast.InMemory.InMemoryProxyBase<TKey, {{receiver.TypeName}}>, {{receiver.TypeName}}
                    where TKey : global::System.IEquatable<TKey>
                {
                    public {{receiver.ProxyName}}InMemoryProxy(global::Cysharp.Runtime.Multicast.InMemory.IReceiverHolder<TKey, {{receiver.TypeName}}> receivers, global::System.Collections.Immutable.ImmutableArray<TKey> excludes, global::System.Collections.Immutable.ImmutableArray<TKey>? targets)
                        : base(receivers, excludes, targets)
                    {
                    }
            """).AppendLine();

        foreach (var method in receiver.Methods)
        {
            EmitMethodSignature(builder, receiver, method);
            builder.Append(" => ");
            if (method.ReturnKind != ReceiverReturnKind.Void)
            {
                builder.Append("base.InvokeWithResult(");
            }
            else
            {
                builder.Append("base.Invoke(");
            }

            AppendArguments(builder, method.Parameters, false);
            if (method.Parameters.Count > 0)
            {
                builder.Append(", ");
            }

            builder.Append("static (receiver");
            for (var i = 0; i < method.Parameters.Count; i++)
            {
                builder.Append($", arg{i + 1}");
            }
            var declaringTypeName = method.DeclaringTypeName ?? receiver.TypeName;
            builder.Append($") => (({declaringTypeName})receiver).{EscapeIdentifier(method.Name)}(");
            for (var i = 0; i < method.Parameters.Count; i++)
            {
                if (i != 0) builder.Append(", ");
                builder.Append($"arg{i + 1}");
            }
            builder.AppendLine("));");
            builder.AppendLine();
        }

        builder.AppendLine("    }").AppendLine();
    }

    private static void EmitRemoteProxy(StringBuilder builder, ReceiverDefinition receiver)
    {
        builder.AppendLine($$"""
                internal sealed class {{receiver.ProxyName}}RemoteProxy : global::Cysharp.Runtime.Multicast.Remoting.RemoteProxyBase, {{receiver.TypeName}}
                {
                    public {{receiver.ProxyName}}RemoteProxy(
                        global::Cysharp.Runtime.Multicast.Remoting.IRemoteReceiverWriter writer,
                        global::Cysharp.Runtime.Multicast.Remoting.IRemoteSerializer serializer)
                        : base(writer, serializer)
                    {
                    }
            """).AppendLine();

        foreach (var method in receiver.Methods)
        {
            EmitMethodSignature(builder, receiver, method);
            builder.Append(" => ");
            var serializedParameters = method.ReturnKind == ReceiverReturnKind.Void ? method.Parameters : method.Parameters.Where(x => !x.IsCancellationToken).ToArray();

            if (method.ReturnKind == ReceiverReturnKind.Void)
            {
                builder.Append("base.Invoke(");
            }
            else if (method.ReturnKind == ReceiverReturnKind.Task)
            {
                builder.Append("base.InvokeWithResultNoReturnValue");
                AppendGenericArguments(builder, serializedParameters.Select(x => x.TypeName));
                builder.Append('(');
            }
            else
            {
                builder.Append("base.InvokeWithResult");
                AppendGenericArguments(builder, serializedParameters.Select(x => x.TypeName).Concat(new[] { method.ResultTypeName! }));
                builder.Append('(');
            }

            builder.Append($"""
                "{EscapeString(method.Name)}", {method.MethodId}
                """);
            foreach (var parameter in serializedParameters)
            {
                builder.Append($", {EscapeIdentifier(parameter.Name)}");
            }
            if (method.ReturnKind != ReceiverReturnKind.Void)
            {
                var cancellationToken = method.Parameters.FirstOrDefault(x => x.IsCancellationToken);
                var cancellationTokenArgument = cancellationToken == null ? "default" : EscapeIdentifier(cancellationToken.Name);
                builder.Append($", {cancellationTokenArgument}");
            }
            builder.AppendLine(");").AppendLine();
        }

        builder.AppendLine("    }").AppendLine();
    }

    private static void EmitFactory(StringBuilder builder, string factoryName, IReadOnlyList<ReceiverDefinition> receivers)
    {
        builder.AppendLine($$"""
            internal sealed class {{factoryName}} : global::Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory, global::Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory
            {
            """);

        // Each factory owns its proxy types, so overlapping receiver sets cannot collide.
        foreach (var receiver in receivers)
        {
            EmitInMemoryProxy(builder, receiver);
            EmitRemoteProxy(builder, receiver);
        }

        builder.AppendLine($$"""
                internal static readonly {{factoryName}} Instance = new {{factoryName}}();

                private {{factoryName}}()
                {
                }

                public TReceiver Create<TKey, TReceiver>(
                    global::Cysharp.Runtime.Multicast.InMemory.IReceiverHolder<TKey, TReceiver> receivers,
                    global::System.Collections.Immutable.ImmutableArray<TKey> excludes,
                    global::System.Collections.Immutable.ImmutableArray<TKey>? targets)
                    where TKey : global::System.IEquatable<TKey>
                {
                    if (TryCreate(receivers, excludes, targets, out TReceiver proxy))
                    {
                        return proxy;
                    }

                    throw CreateMissingProxyException("in-memory", typeof(TReceiver));
                }

                public bool TryCreate<TKey, TReceiver>(
                    global::Cysharp.Runtime.Multicast.InMemory.IReceiverHolder<TKey, TReceiver> receivers,
                    global::System.Collections.Immutable.ImmutableArray<TKey> excludes,
                    global::System.Collections.Immutable.ImmutableArray<TKey>? targets,
                    out TReceiver proxy)
                    where TKey : global::System.IEquatable<TKey>
                {
            """);

        foreach (var receiver in receivers)
        {
            builder.AppendLine($$"""
                    if (typeof(TReceiver) == typeof({{receiver.TypeName}}))
                    {
                        proxy = (TReceiver)(object)new {{receiver.ProxyName}}InMemoryProxy<TKey>((global::Cysharp.Runtime.Multicast.InMemory.IReceiverHolder<TKey, {{receiver.TypeName}}>)(object)receivers, excludes, targets);
                        return true;
                    }
            """);
        }

        builder.AppendLine("""

                    proxy = default!;
                    return false;
                }

                public TReceiver Create<TReceiver>(
                    global::Cysharp.Runtime.Multicast.Remoting.IRemoteReceiverWriter writer,
                    global::Cysharp.Runtime.Multicast.Remoting.IRemoteSerializer serializer)
                {
                    if (TryCreate(writer, serializer, out TReceiver proxy))
                    {
                        return proxy;
                    }

                    throw CreateMissingProxyException("remote", typeof(TReceiver));
                }

                public bool TryCreate<TReceiver>(
                    global::Cysharp.Runtime.Multicast.Remoting.IRemoteReceiverWriter writer,
                    global::Cysharp.Runtime.Multicast.Remoting.IRemoteSerializer serializer,
                    out TReceiver proxy)
                {
            """);

        foreach (var receiver in receivers)
        {
            builder.AppendLine($$"""
                    if (typeof(TReceiver) == typeof({{receiver.TypeName}}))
                    {
                        proxy = (TReceiver)(object)new {{receiver.ProxyName}}RemoteProxy(writer, serializer);
                        return true;
                    }
            """);
        }

        builder.AppendLine("""

                    proxy = default!;
                    return false;
                }

                private static global::System.InvalidOperationException CreateMissingProxyException(string proxyKind, global::System.Type receiverType)
                    => new global::System.InvalidOperationException(
                        $"No source-generated Multicaster {proxyKind} proxy is available for receiver type '{receiverType}'. " +
                        "Add [MulticasterGeneration(typeof(TReceiver))] to this partial class, or compose it with another generated factory.");
            }
            """).AppendLine();
    }

    private static void EmitAnchor(StringBuilder builder, string anchorName, string factoryName)
    {
        builder.AppendLine($$"""
            partial class {{EscapeIdentifier(anchorName)}}
            {
                /// <summary>Gets the generated in-memory proxy factory for this receiver set.</summary>
                public static global::Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory InMemoryProxyFactory { get; } = {{factoryName}}.Instance;

                /// <summary>Gets the generated remote proxy factory for this receiver set.</summary>
                public static global::Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory RemoteProxyFactory { get; } = {{factoryName}}.Instance;
            }
            """);
    }

    private static void EmitMethodSignature(StringBuilder builder, ReceiverDefinition receiver, ReceiverMethodDefinition method)
    {
        var declaringTypeName = method.DeclaringTypeName ?? receiver.TypeName;
        builder.Append($"        {method.ReturnTypeName} {declaringTypeName}.{EscapeIdentifier(method.Name)}(");
        for (var i = 0; i < method.Parameters.Count; i++)
        {
            if (i != 0) builder.Append(", ");
            var parameter = method.Parameters[i];
            builder.Append($"{parameter.TypeName} {EscapeIdentifier(parameter.Name)}");
        }
        builder.Append(')');
    }

    private static void AppendArguments(StringBuilder builder, IReadOnlyList<ReceiverParameterDefinition> parameters, bool excludeCancellationToken)
    {
        var first = true;
        foreach (var parameter in parameters)
        {
            if (excludeCancellationToken && parameter.IsCancellationToken) continue;
            if (!first) builder.Append(", ");
            builder.Append(EscapeIdentifier(parameter.Name));
            first = false;
        }
    }

    private static void AppendGenericArguments(StringBuilder builder, IEnumerable<string> arguments)
    {
        var values = arguments.ToArray();
        if (values.Length == 0) return;
        builder.Append($"<{string.Join(", ", values)}>");
    }

    private static string EscapeIdentifier(string value) => Keywords.Contains(value) ? "@" + value : value;

    private static string EscapeString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string Sanitize(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }
        return builder.ToString();
    }

    private static readonly HashSet<string> Keywords = new HashSet<string>(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class",
        "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event",
        "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object",
        "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return",
        "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
        "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while", "add", "alias", "and", "ascending", "async", "await", "by", "descending",
        "dynamic", "equals", "file", "from", "get", "global", "group", "init", "into", "join", "let", "managed",
        "nameof", "not", "notnull", "on", "or", "orderby", "partial", "record", "remove", "required", "scoped",
        "select", "set", "unmanaged", "value", "var", "when", "where", "with", "yield"
    };
}
