// <auto-generated/>
#nullable enable
#pragma warning disable CS0108
#pragma warning disable CS0162
#pragma warning disable CS0164
#pragma warning disable CS0219
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8604
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631
#pragma warning disable CS8765
#pragma warning disable CS9074
#pragma warning disable CA1050

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace Multicaster.Tests
{

    partial struct RemoteCompositeGroupProviderProxy
    {

        global::Cysharp.Runtime.Multicast.Remoting.RemoteCompositeGroupProvider target;

        public RemoteCompositeGroupProviderProxy(global::Cysharp.Runtime.Multicast.Remoting.RemoteCompositeGroupProvider target)
        {
            this.target = target;
        }

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_groups")]
        static extern ref readonly global::System.Collections.Concurrent.ConcurrentDictionary<(global::System.Type Type, string name), object> ___groups__(global::Cysharp.Runtime.Multicast.Remoting.RemoteCompositeGroupProvider target);
    }

    internal static class RemoteCompositeGroupProviderProxyyExtensions
    {
        public static global::Multicaster.Tests.RemoteCompositeGroupProviderProxy AsPrivateProxy(this global::Cysharp.Runtime.Multicast.Remoting.RemoteCompositeGroupProvider target)
        {
            return new global::Multicaster.Tests.RemoteCompositeGroupProviderProxy(target);
        }
    }

}
